[[hawkular-services-openshift-template]]
Hawkular Services OpenShift Template
------------------------------------

There are currently two OpenShift templates. The first one, called
`hawkular-services-ephemeral.yaml`, is only for the demo purposes, because
the data is lost during the restarts. The second one, called
`hawkular-services-persistent.yaml`, preserves also the data.

Persistent Template
-------------------

In order to run the Hawkular Services with the persistent template, just run:

[source,bash]
----
ansible-playbook playbook.yaml --ask-sudo-pass
----

NOTE: It asks for the root password because it is necessary for flushing the
      ip tables and creating the directories for persistent volumes.

This runs the Hawkular Services and create two persistent volumes, so
that you do not lose your data when restarting OpenShift.

Ephemeral Template
------------------

If you want to start Hawkular Services and you don’t care about your
data, use:

[source,bash]
----
./startEphemeral.sh
----

If you want to shut it down, just type in `oc cluster down`.

TIP: The behavior of the `startEphemeral.sh` script can be customized by environment variables.
     E.g.: `HAWKULAR_SERVICES_IMAGE="hawkular/hawkular-services:x.y.z.Final" ./startEphemeral.sh`

[[prerequisites]]
Prerequisites
~~~~~~~~~~~~~
When using the ansible playbook, the `ansible`, `origin-clients`, `python2-dnf` and `libselinux-python` packages should
 be installed.

....
sudo dnf install -y ansible python2-dnf libselinux-python origin-clients
....

In fact the ansible playbook ensures the `origin-clients` and
`libselinux-python` packages are installed and if not, it installs them. To be able to do
that it itself requires a package called `python2-dnf` on Fedora (it may be different on other platform).
So technically the minimal requirement is only `ansible` and `python2-dnf` packages and the rest
can be installed by ansible playbook.

If the ansible fails with following error:

....
Ensure that the Docker daemon is running with the following argument: --insecure-registry 172.30.0.0/16
....

… just add the insecure registry entry to the docker deamon
configuration and restart the docker:

Edit `/etc/sysconfig/docker` or `/etc/docker/daemon.json` depending on
your docker and run
`sudo systemctl restart docker`.

[[troubleshooting]]
Troubleshooting
~~~~~~~~~~~~~~~

To see what is happening in the oc cluster, you can do:

[source,bash]
----
watch oc get all
----

Sometimes when the network was broken and flushing the ip tables didn’t
help, I had to do:

[source,bash]
----
sudo systemctl stop firewalld.service
----

You can see the hawkular-services logs by

[source,bash]
----
oc logs -f `oc get pod -l name=hawkular-services -o custom-columns=:metadata.name`
----

[[additional-info]]
Additional Information
~~~~~~~~~~~~~~~~~~~~~~
The ansible playbook creates two persistent volumes that use the `hostPath` strategy. These PVs are then
used by the hawkular-services and cassandra containers. Using the hostPath is good for demonstration purposes
but in production it is not recommended because it uses the filesystem path from the node, but it is not
guaranteed that the pod will be started on the same node all the time. In one node cluster this is not an issue. If
you need something more production ready, consult the
link:https://kubernetes.io/docs/user-guide/persistent-volumes/#types-of-persistent-volumes[kubernetes documentation].
